"""added session tokens and csrf tokens

Revision ID: 4bec7c1fb62e
Revises: de9740bf7245
Create Date: 2020-06-11 11:25:20.061813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bec7c1fb62e'
down_revision = 'de9740bf7245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csrf_tokens',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('session_tokens',
    sa.Column('sessionID', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('sessionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_tokens')
    op.drop_table('csrf_tokens')
    # ### end Alembic commands ###
