"""setting database correctly

Revision ID: 98feb8c4adc2
Revises: 4bec7c1fb62e
Create Date: 2020-06-11 12:11:56.866327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98feb8c4adc2'
down_revision = '4bec7c1fb62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_tokens', sa.Column('correspondingUserId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_tokens', 'correspondingUserId')
    # ### end Alembic commands ###
